title: The title of your site
logo: /assets/ProfilePic.jpg
description: I am Computer Engineer with a strong interest in the study, research and application of machine learning and deep learning algorithms
show_downloads: false
theme: jekyll-theme-Cayman

